#include <math.h>

/* =========================================================================
 * LCT LEGACY CONTROL: MOUNT CORRECTION
 * Original Author: David Woody (OVRO/LCT)
 * Documented and integrated for Optical Metrology Validation Pipeline
 * ========================================================================= */

#define TURN_PER_ARCSEC (1.0 / 1296000.0)

void mount_correction(const double *p, double az, double el, double *daz, double *del) {
    /*
     * Applies the TPOINT kinematic model to correct the mount in real-time.
     *
     * Inputs:
     * p  - Array containing the 7 telescope mount correction coefficients.
     *      (These are successfully generated by src/optimization/tpoint_optimizer.py)
     *       p = A1: Azimuth Collimation error (")
     *       p[2] = M1: Azimuth-axis encoder offset (")
     *       p[3] = M3: Elevation-axis skew (")
     *       p[4] = M4: North-South axis tilt (")
     *       p[5] = M5: East-West axis tilt (")
     *       p[6] = A2: Elevation Collimation/Encoder offset (")
     *       p[7] = A3: Gravitational deflection error (")
     *
     * az  - Azimuth w.r.t the local horizontal coord. system (radians)
     * el  - Elevation w.r.t the local horizontal coord. system (radians)
     *
     * Outputs:
     * daz - ON THE SKY horizontal to mount correction in azimuth (arcsec)
     * del - horizontal to mount correction in elevation (arcsec)
     */

    // 1. Calculate theoretical Azimuth correction (dAZ)
    *daz = p + 
           p[2] * cos(el) + 
           p[3] * sin(el) - 
           p[4] * sin(az) * sin(el) - 
           p[5] * cos(az) * sin(el);

    // 2. Calculate theoretical Elevation correction (dEL)
    *del = p[6] + 
           p[7] * cos(el) - 
           p[4] * cos(az) + 
           p[5] * sin(az);

    /* 
     * Note: If the low-level servo controllers require the output in 'turns'
     * instead of arcseconds, multiply the final *daz and *del by TURN_PER_ARCSEC.
     */
}
